### ISSUE TITLE
Centrar boton y cambiar palabra en el registro

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#12]
Centrar un poquito mas el boton. Y debe de decir "_registrate_," no "conectate"
![image](https://user-images.githubusercontent.com/39067108/56998032-6dd92500-6b6f-11e9-8a23-c19be440fd1c.png)

asi debe quedar
![image](https://user-images.githubusercontent.com/39067108/56998114-ad077600-6b6f-11e9-9cfe-16687b10adc8.png)

**Comment by giovanniarandaa** [comment]
@chofas Lo que hice fue subir el boton, me he es complicado dejar el boton centrado ya que tendria que hacerlo para todas las resoluciones

**Comment by chofas** [comment]
sale, ya quedo
