### ISSUE TITLE
Espacios en el login

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#13]
colocar mas espaciado entre el "conectate a naranxadul" y el "correo electronico" y subir un poco mas el boton porfas
![image](https://user-images.githubusercontent.com/39067108/56998537-35d2e180-6b71-11e9-895c-189ec6c85a20.png)

**Comment by giovanniarandaa** [comment]
@chofas Subi el botón que quedara abajo de los campos de texto. Ya que me he es complicado dejarlo centrado por la variedad de resoluciones

**Comment by chofas** [comment]
Si, lo que queria es que subieran tantiiito o sea super poquito, por que se veia un tanto diferente que en el xd, ahora lo subieron mucho, te mando ss de como esta y como deberia quedar
![image](https://user-images.githubusercontent.com/39067108/57411193-786c6d80-71b2-11e9-910e-5d710037f2e4.png)

**Comment by chofas** [comment]
ya quedo
