### ISSUE TITLE
Campo para el correo muy largo

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#14]
en la seccion olvidaste tu contraseña, 

- acortar un poco mas el campo del correo electronico
- colocar mas espacio entre ¿olvidaste tu contraseña? y favor de ingresar tu correo electronico
- centrar un poco mas el boton de enviar

![image](https://user-images.githubusercontent.com/39067108/56998616-7d596d80-6b71-11e9-82f3-d06f11150c36.png)

**Comment by giovanniarandaa** [comment]
- [x]  acortar un poco mas el campo del correo electronico
- [x] colocar mas espacio entre ¿olvidaste tu contraseña? y favor de ingresar tu correo electronico
- [x] centrar un poco mas el boton de enviar

**Comment by chofas** [comment]
No se si puedas agregar otro espacio entre "correo elect" y "enviaremos"
tambien despues del punto de la palabra "problema " y el boton de "enviar"
![image](https://user-images.githubusercontent.com/39067108/57411664-d77eb200-71b3-11e9-8756-77d2ef65cc87.png)

**Comment by chofas** [comment]
ya quedo
