### ISSUE TITLE
Reloj de lactancia agregar enter 

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#17]
- colocar un enter despues de la palabra "de" (en el titulo reloj de lactancia)
- La palabra izquieRda esta mal escrita, dice "izquieda" sin la R

![image](https://user-images.githubusercontent.com/39067108/56999145-9bc06880-6b73-11e9-829b-a6c50a35f2d3.png)

**Comment by giovanniarandaa** [comment]
- [x] colocar un enter despues de la palabra "de" (en el titulo reloj de lactancia)
- [x] La palabra izquieRda esta mal escrita, dice "izquieda" sin la R

**Comment by chofas** [comment]
ya quedo
