### ISSUE TITLE
Calendario seccion registro

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#21]
el calendario del parto, en la aparte del registro no me deja seleccionar fechas del calendario, a menos que lo ponga manual.
![image](https://user-images.githubusercontent.com/39067108/57332275-0cb9d000-70e0-11e9-8ab6-a91f7a1a7453.png)

**Comment by giovanniarandaa** [comment]
@chofas Manda video

**Comment by chofas** [comment]
Olvidalo ya sirve
