### ISSUE TITLE
No puedo cambiar de semana en el home

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#22]
en la pate superior del home, en las semanas, no me deja cambiar de semana
![image](https://user-images.githubusercontent.com/39067108/57332649-cb75f000-70e0-11e9-9ba3-7e3ca7c90119.png)

**Comment by giovanniarandaa** [comment]
@chofas Manda video

**Comment by chofas** [comment]
a o que me refiero es que solo deslizandolo funciona, pero si intento dar clic en el numero, no se cambia, no se si me explique
http://recordit.co/GcVrFlr9zy

**Comment by giovanniarandaa** [comment]
@chofas Si te explciaste lo corrijo

**Comment by chofas** [comment]
ya quedo
