### ISSUE TITLE
Centrar los botones de registro e iniciar sesion

### ISSUE THREAD

**Issue by chofas** [TechiesnBeyond/Naraxandul-iOS#5]
en el index, centrar los botones de registro e iniciar sesion, (estan muy arriba y abajo hay espacio muerto)
![image](https://user-images.githubusercontent.com/39067108/56995250-da9bf180-6b66-11e9-8dab-284da85e3b94.png)

**Comment by giovanniarandaa** [comment]
@chofas No podemos centrarlo, podemos hacerlo mas abajo que fue lo que hice

**Comment by chofas** [comment]
vale, ya quedo
